# =========================
# Build stage
# =========================
FROM node:22-slim AS build


# Libs de Compatibilidade para imagem linux-slim
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    make \
    g++ \
    autoconf \
    automake \
    zlib1g-dev \
    libpng-dev \
    bash \
    libvips-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY package.json yarn.lock ./

# pacote necessário para algumas builds no nodejs
# OBS: tem que ser Global a instalacao
RUN yarn global add node-gyp

# Pegamos as dependencias e instalamos a exataversao do package.json
RUN yarn install --frozen-lockfile

# Com este comando podemos executar alguns comando de CLI
# de alguns pacotes como "strapi development" ou "strapi start"
ENV PATH=/opt/app/node_modules/.bin:$PATH

COPY . .

ENV NODE_ENV=production

RUN yarn build


# =========================
# Production stage
# =========================
FROM node:22-slim

RUN apt-get update && apt-get install -y \
    libvips \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production

WORKDIR /opt/app

COPY --from=build /opt/app/package.json ./
COPY --from=build /opt/app/yarn.lock ./

RUN yarn install --production --frozen-lockfile \
    && yarn cache clean

COPY --from=build /opt/app ./

ENV PATH=/opt/app/node_modules/.bin:$PATH


EXPOSE 1337

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=40s \
    --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost:1337/_health || exit 1

CMD ["yarn", "start"]